work_dir: '001_resnet18_Unet_fold0'

data:
  name: 'StealDataset'
  train_dir: '../input/severstal-steel-defect-detection/train_images'
  test_dir: '../input/severstal-steel-defect-detection/test_images'
  sample_submission_path: '../input/severstal-steel-defect-detection/sample_submission.csv'
  train_df_path: '../input/severstal-steel-defect-detection/train.csv'
  params:
    idx_fold: 0
    num_folds: 5
  num_classes: 4

model:
  arch: 'Unet'
  encoder: 'resnet18'
  pretrained: 'imagenet'

train:
  batch_size: 16
  num_epochs: 40

test:
  batch_size: 4
  best_threshold: 0.5
  min_size: [500, 500, 1000, 2000]

transforms:
  train:
    HorizontalFlip: True
    VerticalFlip: True
    Cutout:
      num_holes: 10
      hole_size: 25
    RandomCropScale: True
  test:
    HorizontalFlip: False
    VerticalFlip: False
    Cutout:
      num_holes: 0
      hole_size: 256//10
    RandomCropScale: False

loss:
  name: "BCEDice"

optimizer:
  name: 'RAdam'
  params:
    encoder_lr: 1.0e-5
    decoder_lr: 1.0e-3

scheduler:
  name: 'plateau'

num_workers: 2
device: 'cuda'
